Ulo download button #61
road86/bahis-dash pull request #62
Opened 2023-04-20 11:20 UTC by yokat

## Description

Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).

Don't forget to reference all other pull requests which are associated to this one below: e.g.

closes #issue_number
relates road86/repository_name#issue_number

## Dependency Changes (delete if not applicable)

List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or yarn.lock been updated?

## Testing (delete if not applicable)

Please describe the new tests that have been added for this change along with any additional instructions required to reproduce a successful test and/or a list of any relevant details for your test configuration.

## Documentation (delete if not applicable)

Please describe the new documentation that has been added for this change (is there new user documentation? is there new developer documentation? is the developer documentation purely generated from docstrings in the code?).

## Database Changes (delete if not applicable)

Have any database changes been committed as part of this pull request?

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the road86 Contribution Guide.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.

2023-04-21 11:49 UTC, mixmixmix commented
I've checked and it seem to be working! Would it be easy to customise the name of the file? E.g. it could have the selected upazila name and today's date?

2023-04-23 14:25 UTC, mixmixmix requested changes
Could have the selected upazila name and today's date be added to the output file?

2023-04-25 09:26 UTC, yokat commented
I added this feature. Can I decide, that it is done, or do you need to have a second look?

2023-04-26 09:51 UTC, ChasNelson1990 commented
> I added this feature. Can I decide, that it is done, or do you need to have a second look?

You will also need a new review if you push new commits :-)

2023-04-30 06:53 UTC, mixmixmix requested changes

2023-04-30 06:53 UTC, mixmixmix commented on pages/ULO.py
> +)
I get an error
```
Traceback (most recent call last):
  File "/Users/mix/repos/bahis-dash/pages/ULO.py", line 446, in export
    return dcc.send_data_frame(bahis_subdata.to_csv, str(SelUpa) + "_export_" + str(date.today()) + ".csv")
AttributeError: 'list' object has no attribute 'to_csv'
```

2023-04-30 08:13 UTC, yokat commented on pages/ULO.py
> +)
:(

2023-04-30 08:25 UTC, mixmixmix requested changes
It works now, however I wonder how difficult would that be for the data and the filename to have actual names in place of geocodes?

2023-04-30 08:46 UTC, yokat commented
Would work, but I would keep the geocode, because some upazila names are not unique.

2023-04-30 08:53 UTC, mixmixmix commented
> Would work, but I would keep the geocode, because some upazila names are not unique.

a simple fix would be just to add a number to the end of upazila name. What do you think? A lot of utility value for a small fix!

2023-04-30 09:16 UTC, yokat commented
like this?

2023-05-07 13:05 UTC, mixmixmix approved these changes
brill

2023-05-07 13:06 UTC, merged